runtime: nodejs20  # Use the Node.js version that matches your development environment
env: standard
instance_class: F1  # This can be adjusted based on your needs

service: frontend
#
# Automatic scaling configuration
automatic_scaling:
  min_idle_instances: 0  # Minimum number of idle instances
  max_idle_instances: automatic  # Maximum number of idle instances
  min_pending_latency: automatic  # Minimum latency before scaling up
  max_pending_latency: automatic  # Maximum latency before scaling down

# Environment variables:
env_variables:
  NODE_ENV: 'production'
  # You can add other environment variables here if your frontend needs them

# Handlers for serving static content
handlers:
  - url: /(.*\.(gif|png|jpg|css|js|map))$
    static_files: build/\1
    upload: build/.*\.(gif|png|jpg|css|js|map)$
    secure: always
    redirect_http_response_code: 301

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    secure: always
    redirect_http_response_code: 301

